export const RouteConstants = {
  PROTECTED_ROUTES: [
    'auth',
    'auth/*',
    'transaction',
    'transaction/*',
    'budget',
    'budget/*',
    'goal',
    'goal/*',
    'plan',
    'plan/*',
    'shopping-list',
    'shopping-list/*',
    'partner-room',
    'partner-room/*',
    'reminder',
    'reminder/*',
    'receipt-ai',
    'receipt-ai/*',
    'subscription',
    'subscription/*',
    'budget-limit',
    'budget-limit/*',
    'notification-settings',
    'notification-settings/*',
    'recurring-transaction',
    'recurring-transaction/*',
    'analytics',
    'analytics/*',
    'currency',
    'currency/*',
  ],
} as const;
