export const RouteConstants = {
  PROTECTED_ROUTES: [
    'auth',
    'auth/*',
    'transaction',
    'transaction/*',
    'budget',
    'budget/*',
    'goal',
    'goal/*',
    'shopping-list',
    'shopping-list/*',
    'partner-room',
    'partner-room/*',
    'reminder',
    'reminder/*',
    'receipt-ai',
    'receipt-ai/*',
  ],
} as const;
